var numero1;
var numero2;
var suma;
   numero1=15;
   numero2=19;
  suma=numero1+numero2;
  resta=numero1-numero2;
  dividir=numero1/numero2;
  multiplicar=numero1*numero2;
 console.log("La suma de dos numero es: " +suma);
 console.log("La resta de dos numeros es:" +resta);
 console.log("La division de dos numeros es:" +dividir);
 console.log("La multiplicacion de dos numeros es: " + multiplicar);
